// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/FillEdgeRepro.tsx": () => import("../components/mockups/FillEdgeRepro.tsx"),
  "./components/mockups/PagerRepro.tsx": () => import("../components/mockups/PagerRepro.tsx"),
  "./components/mockups/rnSvgStub.tsx": () => import("../components/mockups/rnSvgStub.tsx"),
  "./components/mockups/rail-diagnostic/PetInfoMeasure.tsx": () => import("../components/mockups/rail-diagnostic/PetInfoMeasure.tsx")
};
